name: "Checker"
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 4 * * 5"
  workflow_dispatch:

jobs:
  checker:
    name: Checker
    runs-on: 'self-hosted'  # Ran out of hours :P
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo ./utils/searxng.sh install packages

      - name: Set up Python
        run: sudo apt install python3

      - name: Install Python dependencies
        run: |
          make V=1 install

      - name: Checker
        run: |
          make search.checker
